<<<<<<< HEAD
spring.application.name=GuildaAventureiros

spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=123456

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=none
#spring.jpa.hibernate.ddl-auto=update
=======
spring.application.name=guildaAventureiros
>>>>>>> 8f4b7c951cd22e54449dae4fb03e01db9c4068c4
